# imagem base do Python 3.13 em sua versão slim (mais recomendada em 2026)
FROM python:3.13-slim

# define o diretório de trabalho dentro do container        
WORKDIR /app

# copia o arquivo carguru.py para o diretório de trabalho
COPY mascararString.py .

# comando para executar o script carguru.py
CMD ["python", "mascararString.py"]
